# Generated by Django 2.0.3 on 2018-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180430_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='通知設定'),
        ),
    ]
