# Generated by Django 2.0.3 on 2018-05-11 13:03

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Picture')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, editable=False, null=True, upload_to='')),
            ],
        ),
    ]
