# Generated by Django 2.0.3 on 2018-06-04 15:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
