# Generated by Django 2.0.3 on 2018-04-14 08:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('markerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Place Name')),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='webmapping/place_img/%y/%m/%d/', verbose_name='Picture')),
            ],
        ),
    ]
